#!/usr/bin/env python3
"""Build YOLO data.yaml from range-test manifests and launch ultralytics YOLOv8n train.

Default: imgsz=640, epochs=30, project under vision/runs/detect_range_v1.
Exports ONNX path documented even if export is skipped (--no-export).

Example:
  python3 tools/train/launch_train.py --epochs 5 --device cpu
  python3 tools/train/launch_train.py --dry-run   # write data.yaml only
"""
from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

VISION_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_NAMES = {0: "shahed_136", 1: "geran_2", 2: "gerbera"}


def write_data_yaml(
    out: Path,
    raw: Path,
    manifests: Path,
    names: dict[int, str],
) -> Path:
    """Write Ultralytics data.yaml pointing at train/val image lists."""
    train_list = manifests / "train.txt"
    val_list = manifests / "val.txt"
    if not train_list.is_file() or not val_list.is_file():
        raise FileNotFoundError(
            f"missing manifests under {manifests}; run split_sets.py first"
        )

    # Ultralytics expects paths relative to `path` or absolute.
    # Remap manifest lines (images/...) to absolute under raw/.
    def abs_list(src: Path, dst: Path) -> int:
        lines = []
        for line in src.read_text().splitlines():
            line = line.strip()
            if not line:
                continue
            p = raw / line
            if not p.is_file():
                # try as already absolute / relative to vision
                p2 = Path(line)
                p = p2 if p2.is_file() else p
            lines.append(str(p.resolve()))
        dst.write_text("\n".join(lines) + ("\n" if lines else ""))
        return len(lines)

    lists_dir = out.parent / "lists"
    lists_dir.mkdir(parents=True, exist_ok=True)
    n_train = abs_list(train_list, lists_dir / "train.txt")
    n_val = abs_list(val_list, lists_dir / "val.txt")
    test_list = manifests / "test.txt"
    n_test = 0
    if test_list.is_file():
        n_test = abs_list(test_list, lists_dir / "test.txt")

    # Labels sit next to images as ../labels/<stem>.txt relative to image —
    # Ultralytics replaces /images/ with /labels/ in the path.
    names_block = "\n".join(f"  {i}: {n}" for i, n in sorted(names.items()))
    text = f"""# Auto-generated by launch_train.py — V1 range-test classes
path: {raw.resolve()}
train: {lists_dir.resolve() / 'train.txt'}
val: {lists_dir.resolve() / 'val.txt'}
{"test: " + str(lists_dir.resolve() / 'test.txt') if n_test else ""}
nc: {len(names)}
names:
{names_block}
"""
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text)
    print(f"data.yaml -> {out} (train={n_train} val={n_val} test={n_test})")
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--raw", type=Path, default=VISION_ROOT / "data" / "raw")
    ap.add_argument("--manifests", type=Path, default=VISION_ROOT / "data" / "manifests")
    ap.add_argument("--data-yaml", type=Path, default=VISION_ROOT / "configs" / "data_range_v1.yaml")
    ap.add_argument("--epochs", type=int, default=30)
    ap.add_argument("--imgsz", type=int, default=640)
    ap.add_argument("--batch", type=int, default=8)
    ap.add_argument("--device", type=str, default="cpu")
    ap.add_argument("--model", type=str, default="yolov8n.pt")
    ap.add_argument("--project", type=Path, default=VISION_ROOT / "runs" / "detect_range_v1")
    ap.add_argument("--name", type=str, default="train")
    ap.add_argument("--dry-run", action="store_true", help="write data.yaml only; no train")
    ap.add_argument("--export-onnx", action="store_true", help="export best.pt to ONNX after train")
    ap.add_argument("--no-export", action="store_true", help="skip ONNX (default unless --export-onnx)")
    args = ap.parse_args()

    data_yaml = write_data_yaml(args.data_yaml, args.raw, args.manifests, DEFAULT_NAMES)
    onnx_stub = VISION_ROOT / "models" / "onnx" / "yolov8n_range_v1.onnx"
    onnx_stub.parent.mkdir(parents=True, exist_ok=True)
    print(f"ONNX export target (stub path): {onnx_stub}")

    if args.dry_run:
        print("dry-run: skipping ultralytics train")
        return 0

    try:
        from ultralytics import YOLO
    except ImportError:
        print(
            "ERROR: ultralytics not installed. Try:\n"
            "  pip install ultralytics\n"
            "Or re-run with --dry-run after ingest/QC/split.",
            file=sys.stderr,
        )
        return 3

    model = YOLO(args.model)
    results = model.train(
        data=str(data_yaml),
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        device=args.device,
        project=str(args.project),
        name=args.name,
        exist_ok=True,
    )
    # best weights
    save_dir = Path(getattr(getattr(results, "save_dir", None), "__str__", lambda: "")() or args.project / args.name)
    # ultralytics returns a Result object; save_dir is on trainer
    best = args.project / args.name / "weights" / "best.pt"
    if not best.is_file():
        # fallback: search
        cands = list(args.project.rglob("best.pt"))
        best = cands[0] if cands else best
    print(f"best weights: {best}")

    do_export = args.export_onnx and not args.no_export
    if do_export and best.is_file():
        m = YOLO(str(best))
        m.export(format="onnx", imgsz=args.imgsz)
        # copy if produced next to best
        produced = best.with_suffix(".onnx")
        if produced.is_file():
            shutil.copy2(produced, onnx_stub)
            print(f"ONNX exported -> {onnx_stub}")
    else:
        print(f"ONNX skipped; intended path: {onnx_stub}")

    note = args.project / args.name / "TRAIN_NOTE.txt"
    note.parent.mkdir(parents=True, exist_ok=True)
    note.write_text(
        f"epochs={args.epochs}\ndevice={args.device}\nbest={best}\nonnx_stub={onnx_stub}\n"
        f"classes=shahed_136,geran_2,gerbera\n"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
