#!/usr/bin/env python3
"""Train Ultralytics YOLOv8n for class-gated Lock (shahed_136, geran_2, gerbera).

Uses vision/.venv ultralytics. Project defaults to training/runs/.
Builds data.yaml from manifests pointing at datasets/raw.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _paths import CLASS_NAMES, CONFIGS, LISTS, MANIFESTS, RAW, RUNS, SMOKE  # noqa: E402


def write_data_yaml(
    out: Path,
    raw: Path,
    manifests: Path,
    names: dict[int, str],
) -> Path:
    train_list = manifests / "train.txt"
    val_list = manifests / "val.txt"
    if not train_list.is_file() or not val_list.is_file():
        raise FileNotFoundError(f"missing manifests under {manifests}")

    def abs_list(src: Path, dst: Path) -> int:
        lines = []
        for line in src.read_text().splitlines():
            line = line.strip()
            if not line:
                continue
            p = raw / line
            if not p.is_file():
                p2 = Path(line)
                p = p2 if p2.is_file() else p
            lines.append(str(p.resolve()))
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_text("\n".join(lines) + ("\n" if lines else ""))
        return len(lines)

    lists_dir = LISTS
    lists_dir.mkdir(parents=True, exist_ok=True)
    tag = manifests.name  # manifests or smoke
    n_train = abs_list(train_list, lists_dir / f"{tag}_train.txt")
    n_val = abs_list(val_list, lists_dir / f"{tag}_val.txt")
    n_test = 0
    test_list = manifests / "test.txt"
    if test_list.is_file():
        n_test = abs_list(test_list, lists_dir / f"{tag}_test.txt")

    names_block = "\n".join(f"  {i}: {n}" for i, n in sorted(names.items()))
    text = f"""# Auto-generated by training/scripts/train.py
path: {raw.resolve()}
train: {(lists_dir / f'{tag}_train.txt').resolve()}
val: {(lists_dir / f'{tag}_val.txt').resolve()}
{"test: " + str((lists_dir / f'{tag}_test.txt').resolve()) if n_test else ""}
nc: {len(names)}
names:
{names_block}
"""
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text)
    print(f"data.yaml -> {out} (train={n_train} val={n_val} test={n_test})")
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--raw", type=Path, default=RAW)
    ap.add_argument("--manifests", type=Path, default=MANIFESTS)
    ap.add_argument("--smoke", action="store_true", help="use datasets/smoke manifests")
    ap.add_argument("--data-yaml", type=Path, default=CONFIGS / "data_train.yaml")
    ap.add_argument("--epochs", type=int, default=30)
    ap.add_argument("--imgsz", type=int, default=640)
    ap.add_argument("--batch", type=int, default=8)
    ap.add_argument("--device", type=str, default="cpu")
    ap.add_argument("--model", type=str, default="yolov8n.pt")
    ap.add_argument("--project", type=Path, default=RUNS)
    ap.add_argument("--name", type=str, default="train")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument(
        "--allow-provisional",
        action="store_true",
        help="document that this run uses provisional labels (smoke)",
    )
    args = ap.parse_args()

    manifests = SMOKE if args.smoke else args.manifests
    data_yaml = write_data_yaml(args.data_yaml, args.raw, manifests, CLASS_NAMES)

    if args.dry_run:
        print("dry-run: skipping train")
        return 0

    try:
        from ultralytics import YOLO
    except ImportError:
        print("ERROR: ultralytics missing in this interpreter", file=sys.stderr)
        print("Use: vision/.venv/bin/python scripts/train.py ...", file=sys.stderr)
        return 3

    if args.allow_provisional:
        print("WARNING: training with provisional full-frame labels — NOT production GO")

    model = YOLO(args.model)
    model.train(
        data=str(data_yaml),
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        device=args.device,
        project=str(args.project),
        name=args.name,
        exist_ok=True,
    )
    best = args.project / args.name / "weights" / "best.pt"
    print(f"best weights: {best}")
    note = args.project / args.name / "TRAIN_NOTE.txt"
    note.write_text(
        f"epochs={args.epochs}\ndevice={args.device}\nbatch={args.batch}\nimgsz={args.imgsz}\n"
        f"best={best}\nallow_provisional={args.allow_provisional}\n"
        f"classes=shahed_136,geran_2,gerbera\nmanifests={manifests}\n"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
